### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' (copyright field)

### ISSUE THREAD

**Issue by m4rc1e** [googlei18n/glyphsLib#61]
Hey folks,

I've been using fontmake on [https://github.com/weiweihuanghuang/Work-Sans](url). This font uses a copyright symbol in the copyright field.

'Copyright © 2015 by Wei Huang. All rights reserved.'

Fontmake didn't like this. The traceback points to glyphsLib/builder.py", line 214, in generate_base_fonts
```
    if copyright:
        ufo.info.copyright = unicode(copyright.decode("utf-8"))
```

If I remove the copyright symbol, it will successfully convert the .glyphs into ufos.

I have the following dependencies installed:
```
python 2.7
defcon==0.1
fonttools==3.0
glyphsLib==1.0
robofab==1.2
wheel==0.24.0
```

If my dependencies are ok and I'm not doing something stupid, I'll happily fix this. I'm guessing it could be the classic 2.7 encode/decode problem.

Regards,
Marc

**Comment by anthrotype** [comment]
hmm, supposedly this should have been fixed with https://github.com/googlei18n/glyphsLib/pull/60

**Comment by m4rc1e** [comment]
Hey Cosimo,

I thought the same.

When I do git log, the last commit was. 

```

commit 729e05e4ac10ae509712f2e00a872a29fdbab505
Merge: c56de92 700d96c
Author: James Godfrey-Kittle <jamesgk19@gmail.com>
Date:   Thu Jul 14 13:22:24 2016 -0700

    Merge pull request #60 from googlei18n/utf8-sources

    Interpret sources as UTF-8
```

**Comment by anthrotype** [comment]
try doing `pip install -U -r requirements.txt` from fontmake's source directory.

The dependency hell is not fixed yet. The version numbers are meaningless, because we don't tag releases very often.

Maybe we should to add something like https://github.com/pypa/setuptools_scm to all the projects that fontmake relies on, so the version string you see in `pip list`, `pip freeze`, etc. is not "0.1" forever since the initial commit, but has some `-dev` suffix and the hash of commit so we can pinpoint them.

But these things take time.

**Comment by m4rc1e** [comment]
I attempted that approach on my first attempt.

Just to double check. I've recloned the fontmake repo, created a new virtualenv and followed the installation instructions. I now have the following dependencies.

```
booleanOperations==0.3
compreffor==0.1.0
cu2qu==1.0
Cython==0.24
defcon==0.1
fontmake==1.0
fontMath==0.2
fonttools==3.0
glyphsLib==1.0
MutatorMath==1.8
ufo2ft==0.1
ufoLib==1.2
wheel==0.24.0
```

Still no luck.

**Comment by anthrotype** [comment]
can you post the full traceback?

**Comment by anthrotype** [comment]
also, python 2 or 3?

**Comment by m4rc1e** [comment]
Python 2.7

    ufos = glyphsLib.build_masters('/Users/marc/Documents/googlefonts/automated_build_proto/Work-Sans/sources/Work Sans.glyphs', master_dir)
  File "build/bdist.macosx-10.11-intel/egg/glyphsLib/__init__.py", line 76, in build_masters
  File "build/bdist.macosx-10.11-intel/egg/glyphsLib/__init__.py", line 60, in load_to_ufos
  File "build/bdist.macosx-10.11-intel/egg/glyphsLib/builder.py", line 104, in to_ufos
  File "build/bdist.macosx-10.11-intel/egg/glyphsLib/builder.py", line 214, in generate_base_fonts
  File "/Users/marc/Documents/glyphsLib/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 10: ordinal not in range(128)

**Comment by anthrotype** [comment]
Ok, the issue is because since #60 glyphsLib parser is decoding the input data using UTF-8 encoding so the parsed data is already unicode strings.
That line in builder.py was still attempting to call `decode` on a unicode string, which on Python 3 is illegal, whereas on Python2 it encodes with default encoding ('ascii') before decoding with the specified encoding. That's why it fails with `UnicodeEncodeError` when attempting to `decode`...
I'll send a patch.

**Comment by m4rc1e** [comment]
Thank you Cosimo!
